# Generated by Django 5.1.1 on 2024-09-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0003_remove_cartitem_toy_cartitem_content_type_and_more'),
    ]

    operations = [
    ]
