# Generated by Django 5.1.1 on 2024-09-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0004_auto_20240916_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='toydrawing',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='toydrawing',
            name='height',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='toydrawing',
            name='width',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
