# Generated by Django 5.1.1 on 2024-09-17 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0006_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessory',
            old_name='descirption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='review',
            name='toy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='toys.toy'),
        ),
    ]
