# Generated by Django 5.1.1 on 2024-09-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0007_rename_descirption_accessory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toydrawing',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='toydrawing',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
