# Generated by Django 5.1.1 on 2024-09-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0008_toydrawing_color_toydrawing_special_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toydrawing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customer_drawings/'),
        ),
    ]
