# Generated by Django 5.1.1 on 2024-09-17 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0009_alter_toydrawing_image'),
    ]

    operations = [
    ]
