# Generated by Django 5.1.1 on 2024-09-17 16:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0010_auto_20240917_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='toydrawing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
    ]
