# Generated by Django 5.1.1 on 2024-09-17 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0011_toydrawing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='toydrawing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 17, 17, 7, 38, 759998, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
