# Generated by Django 5.1.1 on 2024-09-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0020_review_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepagereview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('review_TEXT', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage_review/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
